################################################################
# +----------------------------------------------------------+ #
# |                       PortForwarded                      | #
# |                        By Relism                         | #
# +----------------------------------------------------------+ #
################################################################

################################################################
# ----------------------- Donations <3 ----------------------- #
# ------------ https://github.com/sponsors/Relism ------------ #
################################################################

################################################################
# ----------------------- Source Code ------------------------ #
# --------- https://github.com/Relism/PortForwarded ---------- #
################################################################

ngrok_region: [EU, AP, AU, IN, JP, SA, US, US_CAL_1]
ngrok_token: YOUR_NGROK_TOKEN
discord_webhook_url: (leave blank for no webhook functionality)